chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('ticket/detail/<slug:slug>/chat', views.chat_room, name='chat_room'),
]

helpdeskapp/urls.py
from django.urls import path
from django.views import View
from . import views
from django.contrib.auth import views as auth_views

app_name = 'helpdeskapp'

urlpatterns = [
    #tickets views
    path('', views.user_login, name='login'),
    path('ticket_list/', views.ticket_list, name='ticket_list'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('ticket_list/', views.ticket_list, name='ticket_list'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('ticket/detail/<slug:slug>/', views.ticket_detail, name='ticket_detail'),
    path('ticket/add/', views.ticket_add, name='ticket_add'),
    path('ticket/edit/<slug:slug>/', views.ticket_edit, name='ticket_edit'),
    path('ticket/delete/<slug:slug>/', views.ticket_delete, name='ticket_delete'),
    path('ticket/<slug:slug>/assigned_to/', views.assigned_to, name='assigned_to'),
]

helpdeskproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('helpdeskapp.urls', namespace='helpdeskapp')),
    path('', include('chat.urls', namespace='chat')),
]

helpdeskapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
# Ticket model
class Ticket(models.Model):
    """
    Represents a ticket in the helpdesk application.

    Attributes:
        title (str): The title of the ticket.
        description (str): The description of the ticket.
        status (str): The status of the ticket. Can be one of 'Pending', 'In Progress', or 'Completed'.
        priority (str): The priority of the ticket. Can be one of 'low', 'mid', or 'high'.
        request_type (str): The type of request for the ticket. Can be one of 'Software', 'Hardware', 'Network', or 'Other'.
        created_at (datetime): The date and time when the ticket was created.
        assigned_to (User): The user assigned to the ticket.
        updated_at (datetime): The date and time when the ticket was last updated.
        created_by (User): The user who created the ticket.
        closed_at (datetime): The date and time when the ticket was closed.
        slug (str): The slugified version of the ticket title, used for generating a unique URL.

    Methods:
        save(*args, **kwargs): Overrides the save method to automatically generate a slug if it doesn't exist.
        __str__(): Returns a string representation of the ticket.
        get_absolute_url(): Returns the absolute URL for the ticket detail view.
    """

    statuslist = (
        ('Pending', 'Pending'),
        ('In Progress', 'In Progress'),
        ('Completed', 'Completed'),
    )
    prioritylist = (
        ('low', 'low'),
        ('mid', 'mid'),
        ('high', 'high'),
    )
    request_typelist = (
        ('Software', 'Software'),
        ('Hardware', 'Hardware'),
        ('Network', 'Network'),
        ('Other', 'Other')
    )
    title = models.CharField(max_length=100)
    description = models.TextField()
    status = models.CharField(max_length=100, choices=statuslist, default='Pending')
    priority = models.CharField(max_length=100, choices=prioritylist, default='low')
    request_type = models.CharField(max_length=100, choices=request_typelist, default='Software')
    created_at = models.DateTimeField(auto_now_add=True)
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ticket_assigned_to', null=True, blank=True, default=None)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ticket_created_by')
    closed_at = models.DateTimeField(null=True, blank=True, default=None)
    
    objects = models.Manager() # default manager

    slug = models.SlugField(unique=True, default='default-slug')

    def save(self, *args, **kwargs):
        """
        Overrides the save method to automatically generate a slug if it doesn't exist.
        """
        if not self.id:
            self.slug = slugify(self.title)
            counter = 2
            while Ticket.objects.filter(slug=self.slug).exists():
                self.slug = f"{slugify(self.title)}-{counter}"
                counter += 1
        super().save(*args, **kwargs) # Call the "real" save() method.

    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('helpdeskapp:ticket_detail', args=[self.slug])

helpdeskapp/forms.py
from django import forms
from django.contrib.auth.models import User
from helpdeskapp.models import Ticket


class AddTicketForm(forms.ModelForm):
    title = forms.CharField(max_length=100)
    description = forms.CharField(widget=forms.Textarea)
    priority = forms.ChoiceField(choices=Ticket.prioritylist)
    request_type = forms.ChoiceField(choices=Ticket.request_typelist)
    
    class Meta:
        model = Ticket
        fields = ('title', 'description', 'priority', 'request_type')

class EditTicketForm(forms.ModelForm):
    title = forms.CharField(max_length=100)
    description = forms.CharField(widget=forms.Textarea)
    priority = forms.ChoiceField(choices=Ticket.prioritylist)
    request_type = forms.ChoiceField(choices=Ticket.request_typelist)
    status = forms.ChoiceField(choices=Ticket.statuslist)

    class Meta:
        model = Ticket
        fields = ('title', 'description', 'priority', 'request_type', 'status')

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=100)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    default_group = forms.ChoiceField(choices=[('Defaultuser', 'Defaultuser')], widget=forms.HiddenInput, required=False)

helpdeskapp/views.py
from itertools import chain
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from django.contrib.auth.views import LogoutView
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template import RequestContext
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q
from .forms import AddTicketForm, EditTicketForm, LoginForm, RegisterForm
from .models import Ticket


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.success(request, 'Zalogowano pomyślnie.')
                    return redirect('helpdeskapp:ticket_list')
                else:
                    messages.error(request, 'Konto jest zablokowane.')
            else:
                messages.warning(request, 'Nieprawidłowe dane logowania.')
    else:
        form = LoginForm()
    return render(request, 'helpdeskapp/registration/login.html', {'form': form})


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('helpdeskapp:login')


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if len(cd['username']) > 12 or len(cd['username']) < 4:
                messages.warning(request, 'Nazwa użytkownika musi zawierać od 4 do 12 znaków.')
            elif " " in cd['username']:
                messages.warning(request, 'Nazwa użytkownika nie może zawierać spacji.')
            elif len(cd['password']) < 8:
                messages.warning(request, 'Hasło musi zawierać co najmniej 8 znaków.')
            elif cd['password'] != cd['password2']:
                messages.warning(request, 'Hasła nie są identyczne.')
            elif User.objects.filter(username=cd['username']).exists():
                messages.warning(request, 'Użytkownik o podanej nazwie już istnieje.')
            else:
                user = User.objects.create_user(cd['username'], cd['email'], cd['password'])
                default_group = Group.objects.get(name='Defaultuser')
                user.groups.add(default_group)
                user.save()
                messages.success(request, 'Konto zostało utworzone.')
                return redirect('helpdeskapp:login')
    else:
        form = RegisterForm()
    return render(request, 'helpdeskapp/registration/register.html', {'form': form})


@login_required
def ticket_list(request):
    if request.user.groups.filter(name='Defaultuser').exists():
        tickets = Ticket.objects.filter(created_by=request.user)
        if not tickets:
            messages.warning(request, 'Brak zgłoszeń.')
    else:
        tickets = Ticket.objects.filter(Q(assigned_to=request.user) | Q(assigned_to=None))
        if not tickets:
            messages.warning(request, 'Brak zgłoszeń.')
    paginator = Paginator(tickets, 5)
    page = request.GET.get('page')
    try:
        tickets = paginator.page(page)
    except PageNotAnInteger:
        tickets = paginator.page(1)
    except EmptyPage:
        tickets = paginator.page(paginator.num_pages)
    return render(request, 'helpdeskapp/tickets/ticket_list.html', {'page': page ,'tickets': tickets})


def ticket_detail(request, slug):
    ticket = get_object_or_404(Ticket, slug=slug)
    return render(request, 'helpdeskapp/tickets/ticket_detail.html', {'ticket': ticket})


def ticket_add(request):
    if request.method == 'POST':
        form = AddTicketForm(request.POST)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.created_by = request.user
            form.save()
            messages.success(request, 'Zgłoszenie zostało dodane.')
            return redirect('helpdeskapp:ticket_list')  
    else:
        form = AddTicketForm()
    return render(request, 'helpdeskapp/tickets/ticket_add.html', {'form': form})


def ticket_edit(request, slug):
    ticket = get_object_or_404(Ticket, slug=slug)
    if request.method == "POST":
        form = EditTicketForm(request.POST, instance=ticket)
        if form.is_valid():
            ticket = form.save()
            messages.success(request, 'Zgłoszenie zostało zmienione.')
            return redirect('helpdeskapp:ticket_detail', slug=ticket.slug)
    else:
        form = EditTicketForm(instance=ticket)
    return render(request, 'helpdeskapp/tickets/ticket_edit.html', {'form': form})


def ticket_delete(request, slug):
    ticket = get_object_or_404(Ticket, slug=slug)
    ticket.delete()
    messages.success(request, 'Zgłoszenie zostało usunięte.')
    return redirect('helpdeskapp:ticket_list')


def assigned_to(request, slug):
    ticket = get_object_or_404(Ticket, slug=slug)
    if ticket.assigned_to:
        messages.warning(request, 'Zgłoszenie jest już przypisane.')
    if request.user.groups.filter(name='Defaultuser').exists():
        messages.warning(request, 'Nie masz uprawnień do przypisania zgłoszenia.')
    else:
        ticket.assigned_to = request.user
        ticket.save()
        messages.success(request, 'Zgłoszenie zostało przypisane.')

    return redirect('helpdeskapp:ticket_detail', slug=ticket.slug)

helpdeskapp/templates/helpdeskapp/tickets/ticket_add.html
{% load static %}
<head>
    <link href="{% static 'helpdeskapp/ticket_interaction.css' %}" rel="stylesheet">
</head>

<div class="container">
    <div class="left-side">
        <h2>{% block title %} dodaj zgłoszenie {% endblock %}</h2>
    </div>

        {% block content %}
        {% if sent %}
            <h1> Zgłoszenie zostało dodane</h1>
        {% else %}
            <form method="post">
                {% csrf_token %}
                <div class="help-card">
                    {{ form.as_p }}
                </div>
                <input type="submit" value="Dodaj zgłoszenie" class="submit">
            </form>
        {% endif %}
        {% endblock %}
    </div>
</div>

helpdeskapp/templates/helpdeskapp/tickets/ticket_detail.html
{%load static %}
<DOCTYPE html>
<head>
    <link href="{% static 'helpdeskapp/detail.css' %}" rel="stylesheet">
</head>
<body>

    {% for message in messages %}
        <div class="alertwarning">
            {{ message }}
        </div>
    {% endfor %}

{% block content %}
<div class="container">
    <div class="help-card">
        <h1>Tytuł: {{ticket.title}}</h1>
        <p>Opis: {{ticket.description}}</p>
        <p>status: {{ticket.status}}</p> 
        <p>prioritet: {{ticket.priority}}</p>
        <p>rodzaj problemu: {{ticket.request_type}}</p>
        <p>stworzono przez: {{ticket.created_by}}</p>
        <p>Stworzono ticket: {{ticket.created_at}}</p>
        <p>Zaktualizowano: {{ticket.updated_at}}</p>
        <p>Przypisany do: {{ticket.assigned_to}}</p>
        <div class="a_other">
        <p><a href="{% url 'helpdeskapp:assigned_to' ticket.slug %}" >Przypisz do mnie</a></p>
        <p><a href = "{% url 'helpdeskapp:ticket_list' %}" >Powrót do listy ticketów</a></p>
        <p><a href="{% url 'helpdeskapp:ticket_edit' ticket.slug %}" >Edytuj ticket</a></p>
        <p><a href="{% url 'chat:chat_room' ticket.slug %}" >Przejdź do czatu</a></p>
        </div>  
        <p class="usun"><a href="{% url 'helpdeskapp:ticket_delete' ticket.slug %}" class = "usun">Usuń ticket</a></p>
        
    </div>
    

</div>
{% endblock %}
</body>

helpdeskapp/templates/helpdeskapp/tickets/ticket_edit.html
{%load static %}
{% block content %}
<head>
  <link href="{% static 'helpdeskapp/ticket_interaction.css' %}" rel="stylesheet">
</head>
<div class="container">
  <h2>Edit ticket</h2>
  <form action = "" method="POST">
    {% csrf_token %}
    <div class="help-card">
      {{ form.as_p }}
    </div>
    <button type="submit" class="submit">Zapisz Dane</button>
  </form>
</div>
{% endblock %}

helpdeskapp/templates/helpdeskapp/tickets/ticket_list.html
{% extends "helpdeskapp/base.html" %}
{%block title%} Tickety {%endblock%}
{% block content %}
{%load static%}
<head>
    <link href="{% static 'helpdeskapp/main.css' %}" rel="stylesheet">
</head>
<p class="add">
    <a href="{% url 'helpdeskapp:ticket_add' %}">Stwórz nowe zgłoszenie</a>
</p>
<div class="tickets">
    
    <div class="container">
       
        {% for ticket in tickets%}

        <a href="{{ticket.get_absolute_url}}">
        <div class="card">

            <h2>Tytuł:{{ticket.title}}</h2>
            <p>prioritet: {{ticket.priority}}</p>
            <p>rodzaj problemu: {{ticket.request_type}}</p>
            <p>Stworzono przez: {{ticket.created_by}}</p>
            <p>Stworzono ticket: {{ticket.created_at}}</p>

        </div>
        </a>
        {%endfor%}
    </div>
    {%include "helpdeskapp/pagination.html" with page=tickets %}
</div>

{% endblock %}